"""Adapt Room model

Revision ID: 368fb3bbfddc
Revises: 461fa1ecc4c7
Create Date: 2024-11-02 22:58:57.624360

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "368fb3bbfddc"
down_revision = "461fa1ecc4c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
