"""Add SensorScheduleModel

Revision ID: 37a495f815ff
Revises: 83290f1c35ee
Create Date: 2024-11-02 11:05:04.130217

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '37a495f815ff'
down_revision = '83290f1c35ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_schedule')
    # ### end Alembic commands ###
