"""Add SensorStatisticModel

Revision ID: 461fa1ecc4c7
Revises: 37a495f815ff
Create Date: 2024-11-02 11:28:09.315742

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '461fa1ecc4c7'
down_revision = '37a495f815ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('average_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_statistic')
    # ### end Alembic commands ###
