"""Add user_id in Sensor Statistic model

Revision ID: de8325571150
Revises: 47d3f4666acd
Create Date: 2024-11-03 16:38:10.216340

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de8325571150"
down_revision = "47d3f4666acd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor_statistic", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor_statistic", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
